#ifndef _DRIVE_PCI_CLASSCODE_H
#define _DRIVE_PCI_CLASSCODE_H

#define CLASSCODE_MASS_STORAGE      0x01
    #define SUBCLS_MASS_STORAGE_SATA    0x06
        #define SUBCLS_MASS_STORAGE_SATA_VENDOR_SPEC    0x00
        #define SUBCLS_MASS_STORAGE_SATA_AHCI           0x01
        #define SUBCLS_MASS_STORAGE_SATA_SSBI           0x01
    #define SUBCLS_MASS_STORAGE_SAS     0x07
        #define SUBCLS_MASS_STORAGE_SAS                 0x00
    #define SUBCLS_MASS_STORAGE_NVM     0x08
        #define SUBCLS_MASS_STORAGE_NVM_NVMHCI          0x01
        #define SUBCLS_MASS_STORAGE_NVM_NVME            0x02
    #define SUBCLS_MASS_STORAGE_UFS     0x09
    #define SUBCLS_MASS_STORAGE_OTHER   0x80

#endif //_DRIVE_PCI_CLASSCODE_H